config/routes.rb
Rails.application.routes.draw do
  resources :super_admins
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :super_admin
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/super_admins_controller.rb
class SuperAdminsController < ApplicationController
  before_action :set_super_admin, only: [:show, :edit, :update, :destroy]

  # GET /super_admins
  # GET /super_admins.json
  def index
    @super_admins = SuperAdmin.all
  end

  # GET /super_admins/1
  # GET /super_admins/1.json
  def show
  end

  # GET /super_admins/new
  def new
    @super_admin = SuperAdmin.new
  end

  # GET /super_admins/1/edit
  def edit
  end

  # POST /super_admins
  # POST /super_admins.json
  def create
    @super_admin = SuperAdmin.new(super_admin_params)

    respond_to do |format|
      if @super_admin.save
        format.html { redirect_to @super_admin, notice: 'Super admin was successfully created.' }
        format.json { render :show, status: :created, location: @super_admin }
      else
        format.html { render :new }
        format.json { render json: @super_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /super_admins/1
  # PATCH/PUT /super_admins/1.json
  def update
    respond_to do |format|
      if @super_admin.update(super_admin_params)
        format.html { redirect_to @super_admin, notice: 'Super admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @super_admin }
      else
        format.html { render :edit }
        format.json { render json: @super_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /super_admins/1
  # DELETE /super_admins/1.json
  def destroy
    @super_admin.destroy
    respond_to do |format|
      format.html { redirect_to super_admins_url, notice: 'Super admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_super_admin
      @super_admin = SuperAdmin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def super_admin_params
      params.require(:super_admin).permit(:username, :email)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/super_admins_helper.rb
module SuperAdminsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/super_admins/_form.html.erb
<%= form_for(super_admin) do |f| %>
  <% if super_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(super_admin.errors.count, "error") %> prohibited this super_admin from being saved:</h2>

      <ul>
      <% super_admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/super_admins/edit.html.erb
<h1>Editing Super Admin</h1>

<%= render 'form', super_admin: @super_admin %>

<%= link_to 'Show', @super_admin %> |
<%= link_to 'Back', super_admins_path %>

app/views/super_admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Super Admins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @super_admins.each do |super_admin| %>
      <tr>
        <td><%= super_admin.username %></td>
        <td><%= super_admin.email %></td>
        <td><%= link_to 'Show', super_admin %></td>
        <td><%= link_to 'Edit', edit_super_admin_path(super_admin) %></td>
        <td><%= link_to 'Destroy', super_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Super Admin', new_super_admin_path %>

app/views/super_admins/new.html.erb
<h1>New Super Admin</h1>

<%= render 'form', super_admin: @super_admin %>

<%= link_to 'Back', super_admins_path %>

app/views/super_admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @super_admin.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @super_admin.email %>
</p>

<%= link_to 'Edit', edit_super_admin_path(@super_admin) %> |
<%= link_to 'Back', super_admins_path %>